### ISSUE TITLE
data: create data container for nessus scans, results, reports, policies

### ISSUE THREAD

**Issue by sometheycallme** [cleanerbot/docker-nessus#12]
@jumanjiman @jcwx @vpalacio 

This issue is to create a separate data container for the nessus results.   It will also serve as the "data grabber" point for parsing the scan results and consuming them in a SIEM (like Splunk)

**Comment by jcwx** [comment]
This is what I did in order to create a data container.  There isn't much to it, just an empty space where a directory named `/opt/nessus-persist` is located.

https://github.com/jcwx/docker-nessus/blob/master/Dockerfile.nessus-persist

In order to start the data container:

docker run -i -t --name nessus-persist core/nessus-persist

Then to mount the volumes in the data container in the Nessus container.

docker run -p 8834:8834 -d --volumes-from nessus-persist core/nessus

That data container is crude, and I need to figure out how to build it in a way other than I have as once it is initially launched it opens a shell (which, of course it is instructed to do).  Then one has to exit the shell, which stops the container, at which point the container needs to be restarted.  I'm sure we'll come up with a better solution than that.

**Comment by jcwx** [comment]
Something we'll have to do is come up with a way to record the MAC address used when the initial Nessus install occurs, and record that somewhere in the data container.  

The way I see the flow once a Nessus instance is needed.

* check for existence of data container
* if no data container, build it
* if data container does exist, mount and retrieve the MAC associated with the Nessus install
* build Nessus container, built with the MAC from the data container and the `-d --volumes-from` flag
* if a fresh install, the MAC address of the Nessus container is to be recorded in the data container

I have a rudimentary check for determining if the data container has an instance of Nessus.  If it does not exist, the fresh Nessus install is copied to the data container.  If the install does exist, the location where Nessus was installed at /opt/nessus is deleted, and a soft link to the /opt/nessus-persist  directory on the data container is created (/opt/nessus <-> /opt/nessus-persist).  The data container is populated with a fresh instance of the install if needed, or the existing data is preserved and made accessible.

**Comment by jcwx** [comment]
We'll need to determine how to mount and retrieve information, which, in this case, is a record of the MAC address associated with the Nessus install from the data container before the Nessus container is built.

**Comment by jcwx** [comment]
http://docs.docker.com/userguide/dockervolumes/

**Comment by jcwx** [comment]
One option might be to spoof the MAC address after the container is created, This could be done in a script such as the startup script I created, as that is after the persist data volume/container is created but before Nessus has started.  This would avoid having to mount the data container before creating the Nessus container.  

http://xmodulo.com/spoof-mac-address-network-interface-linux.html

**Comment by jcwx** [comment]
I found that even when stopping/restarting a docker container the MAC address changes.

**Comment by jcwx** [comment]
My Nessus container stopped during the process of downloading the plugins.  That is where I restarted it and realized the MAC address changed.  I stopped the container, deleted it, created a new one with the `--mac-address` set to the MAC on the original Nessus container.  

I was able to complete the plugin download at that point and log in.

```
core@localhost ~ $ docker logs -f 8c3f9dfe6fa2
nessusd (Nessus) 6.4.3 [build M20035] for Linux
Copyright (C) 1998 - 2015 Tenable Network Security, Inc

Processing the Nessus plugins...
[##################################################]

All plugins loaded (564sec)
```

**Comment by jcwx** [comment]
I completed a scan of my lan.  Nessus seems to be functioning properly.

I then stopped the Nessus container, deleted it and then built a new one.

```
core@localhost ~ $ docker ps -a
CONTAINER ID        IMAGE                                                              COMMAND                  CREATED             STATUS                    PORTS                    NAMES
8c3f9dfe6fa2        core/nessus                                                        "/bin/bash /root/star"   21 minutes ago      Up 21 minutes             0.0.0.0:8834->8834/tcp   thirsty_blackwell
c59518ee4113        48cf6138fe524377facdeac25000314e561417d4120e6af30c669ce342f86fee   "/bin/sh -c 'rpm -ivh"   10 hours ago        Exited (0) 10 hours ago                            hungry_raman
2d8bdcfd5fc8        core/nessus-persist                                                "/bin/sh -c /bin/sh"     17 hours ago        Up 10 hours                                        nessus-persist
core@localhost ~ $ docker stop 8c3f9dfe6fa2
8c3f9dfe6fa2
core@localhost ~ $ docker rm 8c3f9dfe6fa2
8c3f9dfe6fa2
core@localhost ~ $ docker run -p 8834:8834 --mac-address 02:42:ac:11:00:01 -d --volumes-from nessus-persist core/nessus
349e81b3a3d96b0e9fa2340e73dd70e59eedf51a3b5db092f9d421ad7c4e0788
core@localhost ~ $ docker ps -a
CONTAINER ID        IMAGE                                                              COMMAND                  CREATED             STATUS                    PORTS                    NAMES
349e81b3a3d9        core/nessus                                                        "/bin/bash /root/star"   7 seconds ago       Up 6 seconds              0.0.0.0:8834->8834/tcp   admiring_ardinghelli
c59518ee4113        48cf6138fe524377facdeac25000314e561417d4120e6af30c669ce342f86fee   "/bin/sh -c 'rpm -ivh"   10 hours ago        Exited (0) 10 hours ago                            hungry_raman
2d8bdcfd5fc8        core/nessus-persist                                                "/bin/sh -c /bin/sh"     17 hours ago        Up 10 hours                                        nessus-persist
```

Nessus started properly and provided the login screen.

```
core@localhost ~ $ docker logs -f 349e81b3a3d9
nessusd (Nessus) 6.4.3 [build M20035] for Linux
Copyright (C) 1998 - 2015 Tenable Network Security, Inc

Processing the Nessus plugins...
[##################################################]

All plugins loaded (578sec)
```

![untitled](https://cloud.githubusercontent.com/assets/1878474/10388792/efd9ea98-6e3a-11e5-8d49-bd1127ce8752.jpg)


I logged in and found the scan I had run on the previous Nessus scan is present.

**Comment by sometheycallme** [comment]
Cool, lets see if we can incorporate the nessus data volume into the docker-nessus repo.
