### ISSUE TITLE
Data: Create Data Grabber Container -- Move Scan Data From Nessus to Splunk

### ISSUE THREAD

**Issue by jcwx** [cleanerbot/docker-nessus#14]
This container is intended to migrate scan data from a Nessus docker container to the Splunk indexers/rsyslog servers.

Nessus presently uses python scripts to move and prepare the data for Splunk.  The scripts are accessible in puppet under the Splunk deployment server.

**Comment by jcwx** [comment]
This appears to be the python script that extracts the data from the Nessus API and sends it on the way to Splunk.

https://github.com/ISEexchange/puppet/blob/b81f6db7e61ccec0f5a08a503d99d790a98bc2d0/modules/splunk/files/id-imap01/getXMLNessus.py

**Comment by jcwx** [comment]
Sanitized for your protection.

```
[root@id-imap01 cron.d]# cat run_getXMLNessus 
0 5 * * * root /usr/bin/python /opt/nessus/external-scripts/py-nessus-wrapper/getXMLNessus.py "https://xxx:8834" "admin" "blah_blah" "/data/nessus/in" "/data/nessus/out"
```

**Comment by sometheycallme** [comment]
@jcwx 

Lets move this issue into our private repo to freely discuss the subtle items in our enterprise separate from repository.

once we are solid on our approach, we can scrub the content for public use and place it into the repo (e.g . a generic data grabber.)
