### ISSUE TITLE
issue: nessus license not valid when moving container around

### ISSUE THREAD

**Issue by sometheycallme** [cleanerbot/docker-nessus#23]
> Nessus and plugins are loading but the license is invalid, even when using the same MAC address. It is not possible to use it as backups.

from #20

**Comment by Passe12345** [comment]
Indeed, when i commit and save the two images (e.g nessus:licensed and nessus-unlicensed-data) and try to load on another docker server, the license is not recognized as valid. Of course, the specified MAC address is the same.

Does anyone experienced the same issue ?

**Comment by sometheycallme** [comment]
Not yet, I haven't tried moving the image around (we are actually starting to think about orchestration of a scanning image) so this might provide some proving ground.

**Comment by sometheycallme** [comment]
keep this issue open and posted.

**Comment by sometheycallme** [comment]
haven't forgotten about this - WIP

**Comment by ikoniaris** [comment]
+1

**Comment by sometheycallme** [comment]
#26
