### ISSUE TITLE
Why not using --net host?

### ISSUE THREAD

**Issue by sapran** [cleanerbot/docker-nessus#30]
Guys, thanks for the great job. One quick question: don't you think that giving the container access to host network is kind of better? Will eliminate a lot of need for additional configuration of network access, proxy etc.

**Comment by sometheycallme** [comment]
Hey @sapran do you mean ```docker run --net=host```

**Comment by sometheycallme** [comment]
If I remember right, nessus ties it's registration to the MAC.  If we run with --net=host, we cannot pin to a mac

```
docker run -d --net=host --name unlicensednessus -p 8834:8834 --mac-address 02:42:ac:11:00:01 docker-nessus
docker: Error response from daemon: conflicting options: mac-address and the network mode.
```

**Comment by jcwx** [comment]
Tim is correct -- if you're planning on restoring an instance and plan on using an existing license it is necessary to retain the MAC that was previously used.  

I used this to generate a docker instance on a different docker/nessus project, but similar requirements.

```docker run -p 8834:8834 --mac-address F4:CE:46:XX:XX:XX --name=nessus -d nessus```

I'm not sure what is meant by "access to host network".  The -p flag binds to a port on the host where the docker container is running,  I have access to the service on port 8834 on the CoreOS host where the instance exists.  Accessing it is a matter of https://blah.blahblah.blah:8834

**Comment by sometheycallme** [comment]
resolved: don't use net-host because you can't pin the mac-address.
