### ISSUE TITLE
use 64-bit package instead of 32-bit

### ISSUE THREAD

**Issue by jumanjiman** [cleanerbot/docker-nessus#7]
current: Nessus-6.3.7-es6.i386.rpm

should: x86_64 rpm

**Comment by sometheycallme** [comment]
@jumanjiman 

Picking this one up

**Comment by sometheycallme** [comment]
https://github.com/cleanerbot/docker-nessus/pull/9

**Comment by sometheycallme** [comment]
done. see pul request and test.
