### ISSUE TITLE
start nessus with license and commit

### ISSUE THREAD

**Issue by sometheycallme** [cleanerbot/docker-nessus#8]
@vpalacio @jumanjiman 

This issue is to track creating data containers for nessusd running on in container.

**Comment by sometheycallme** [comment]
@jcwx 

The latest pull request #9 add support for running nessus home edition on version 6.4.3 64 bit version.

docker initializes and a home key activation is passed when launched.

This issue is to separate the startup of nessus into it's own data container.

**Comment by sometheycallme** [comment]
http://static.tenable.com/documentation/Nessus_Activation_Code_Installation.pdf

**Comment by jcwx** [comment]
@sometheycallme 

I was looking through my version of the nessus docker container and see that I was manually creating a data container.  I have the Dockerfile for it as well on the ChromeOS VM I'm using.

Looking at what I did with the `startup.sh` script, I'll add some context for it here as I didn't comment it at all.

```
#!/bin/sh
#
# This checks to see if there is an existing nessus
# install in the data container.  If there is not a 
# directory named /opt/nessus-persist/nessus/var
# (thus indicating the data container is new as well)
# the fresh install of Nessus on the newly created
# container is copied to the data container and
# the original install location is deleted.  Nessus
# is now solely installed on the data container
#
# The second part of the script is executed, where 
# the data container directory is soft linked to the
# standard install location on the new container.
# 
# 
if [ ! -f /opt/nessus-persist/nessus/var ]; then
    /bin/cp -a /opt/nessus /opt/nessus-persist
    /bin/rm -rf /opt/nessus
fi

/bin/ln -s /opt/nessus-persist/nessus /opt/nessus
/opt/nessus/sbin/nessusd
```

**Comment by jcwx** [comment]
The way I set up the data container in my config, it will retain the whole Nessus installation, including keys and any users or other customization.  This worked fine, but once the Nessus container was deleted and rebuilt, the license key was considered corrupted.  The way I went about it was intended to preserve everything from the original install.  This is accessed through the soft link to the data container.

Also, as I recall, the only thing that didn't work on the rebuilt Nessus container was the signature updates (due to the license problem), but I could run scans and review existing.

**Comment by sometheycallme** [comment]
### procedure for registering nessus scanner and committing the container

I'm going to dissect the registration process.

1) I start the nessusd container from this repo or pulled from Docker Hub. (sometheycallme/nessus)
<img width="892" alt="screenshot 2015-10-06 15 21 57" src="https://cloud.githubusercontent.com/assets/630113/10320247/85c33e08-6c40-11e5-8bb0-b0f5bfd6406c.png">
and the DRM wall is up and running
<img width="782" alt="screenshot 2015-10-06 15 22 47" src="https://cloud.githubusercontent.com/assets/630113/10320253/90c6e07a-6c40-11e5-9380-8b2add37706f.png">
2) I exec into the nessusd container 
<img width="792" alt="screenshot 2015-10-06 15 26 28" src="https://cloud.githubusercontent.com/assets/630113/10320271/a567521c-6c40-11e5-88e6-3aa73eed4922.png">
3) I run the cli to obtain hash for registering the product offline
```/opt/nessus/sbin/nessuscli fetch –-challenge```
<img width="875" alt="screenshot 2015-10-06 15 24 29" src="https://cloud.githubusercontent.com/assets/630113/10320293/b76ccb04-6c40-11e5-9632-6939e9208b27.png">
4) I go to the license generator site with the challenge and the activation code sent to my registration email (blacked out)
![register-01](https://cloud.githubusercontent.com/assets/630113/10341104/545b3d1a-6ce1-11e5-95f2-ae8c5a4a4396.png)
5) It spits out the license. I create nessus.license in the container  ```/opt/nessus/etc/nessus/nessus.license```

<img width="859" alt="screenshot 2015-10-06 15 38 45" src="https://cloud.githubusercontent.com/assets/630113/10320339/f5d15a90-6c40-11e5-84ba-95491b03a76e.png">

6) I register nessus offline with the license file above
<img width="859" alt="screenshot 2015-10-06 15 38 45" src="https://cloud.githubusercontent.com/assets/630113/10341145/88d7de72-6ce1-11e5-9812-48414242f9f4.png">

7) I created a local admin user, and the registration is fine.  Scanner is up an running
<img width="872" alt="screenshot 2015-10-06 15 39 12" src="https://cloud.githubusercontent.com/assets/630113/10341160/9f277e94-6ce1-11e5-98e9-80fd8c83caec.png">

### Commit the license key to the container

1) At this point, if you destroy the container, you will lose the registration and have to start all over.

check for the running container ID and stop it

```shell
docker ps
docker stop <container ID>
```
<img width="893" alt="screenshot 2015-10-06 15 45 19" src="https://cloud.githubusercontent.com/assets/630113/10341201/c0afed30-6ce1-11e5-8abe-c5b5b0540e0b.png">


2) After you stop the container, commit the change

```docker commit <container ID> <image-name>```

<img width="892" alt="screenshot 2015-10-06 15 47 27" src="https://cloud.githubusercontent.com/assets/630113/10341254/ffe0d17c-6ce1-11e5-9f99-56589a40aa6d.png">


### Restart the container

Be sure to name the committed container something different than the previous image name.

<img width="886" alt="screenshot 2015-10-07 10 56 55" src="https://cloud.githubusercontent.com/assets/630113/10341310/328bf2dc-6ce2-11e5-825d-97a5c8f9103f.png">

**Comment by sometheycallme** [comment]
>The way I set up the data container in my config, it will retain the whole Nessus installation, including keys and any users or other customization.

It is possible to create a committed docker container with the post installation of keys and user information so that we can use the public docker image for nessus (here) and customize a container for our use and enterprise license keys.

Step 2 above in "commit the container"

**Comment by sometheycallme** [comment]
Our changing of license keys is infrequent.  And our nessus upgrades also do not occur often.

**Comment by jcwx** [comment]
I agree the key change is seldom needed -- however, even though I could start and operate Nessus after the shutting down and restarting the Nessus container, the license key/hash used to retrieve the signatures was not accepted by the server at Nessus.  I seem to recall it considered the key corrupted or installed on different hardware.

**Comment by jcwx** [comment]
I'm reviewing the process that I had and adapting it to the newer Nessus release.  Had to manually start the data container as I'd mentioned.

```
core@localhost ~ $ docker run -i -t --name nessus-persist core/nessus-persist
/ # exit
core@localhost ~ $ docker ps -a
CONTAINER ID        IMAGE                 COMMAND                CREATED              STATUS                          PORTS               NAMES
c7d8713824d0        core/nessus-persist   "/bin/sh -c /bin/sh"   About a minute ago   Exited (0) About a minute ago                       nessus-persist
core@localhost ~ $ docker start c7d8713824d0
c7d8713824d0
core@localhost ~ $ docker ps -a
CONTAINER ID        IMAGE                 COMMAND                CREATED             STATUS              PORTS               NAMES
c7d8713824d0        core/nessus-persist   "/bin/sh -c /bin/sh"   2 minutes ago       Up 2 seconds                            nessus-persist
```

Then on to the Nessus container.

```
core@localhost ~ $ docker run -p 8834:8834 -d --volumes-from nessus-persist core/nessus
a7b9b9f88b018b3c7ad04d399379d6d8169eb01a8a3517d4ba5ea58f54cac7a6
core@localhost ~ $ docker ps -a
CONTAINER ID        IMAGE                 COMMAND                  CREATED             STATUS              PORTS                    NAMES
a7b9b9f88b01        core/nessus           "/bin/bash /root/star"   7 seconds ago       Up 6 seconds        0.0.0.0:8834->8834/tcp   sharp_poincare
c7d8713824d0        core/nessus-persist   "/bin/sh -c /bin/sh"     6 minutes ago       Up 4 minutes                                 nessus-persist
```

Which brings me to an accessible Nessus install window.  I'll have to reset my home user Nessus license in order to push forward.

![untitled](https://cloud.githubusercontent.com/assets/1878474/10342741/872b6786-6ce8-11e5-8b17-d9abc571ef40.jpg)

**Comment by sometheycallme** [comment]
>however, even though I could start and operate Nessus after the shutting down and restarting the Nessus container, the license key/hash used to retrieve the signatures was not accepted by the server at Nessus. I seem to recall it considered the key corrupted or installed on different hardware.

Yes you are right.

If you destroy the container with ```docker rm``` or ```docker rim``` and then ```docker build``` or ```docker run``` the new build, attempting to use the same registration key sent to you will NOT work.   

The hash that nessus generates to register the scanner that you intend to use is tied to the installation.   

To preserve the container with the license key registration, you need to commit the changes to the container (after stopping NOT deleting or removing it).

https://github.com/wsargent/docker-cheat-sheet/blob/master/README.md

https://docs.docker.com/reference/commandline/rm/

**Comment by sometheycallme** [comment]
I am in the process of creating a shell script that captures about 10 steps required to create a functional "enterprise ready" nessus scanner.

It will NOT be in this repository, as it will have our enterprise license keys tied to it.

**Comment by sometheycallme** [comment]
Also fwiw - right now the size of the docker container for Nessus is ~1.5GB.   I anticipate that after we add scan templates and such, that it will be much larger.

**Comment by sometheycallme** [comment]
Running on CoreOS - @jumanjiman has pointed out that because CoreOS uses [BTRFS](https://coreos.com/os/docs/latest/btrfs-troubleshooting.html)  the size restriction is really limited to storage on the server which you are running CoreOS

**Comment by jcwx** [comment]
Nah, not mine -- It's running on a Virtual Box VM at home.

**Comment by sometheycallme** [comment]
After committing the changes and restarting the container, it does not like the registration.....

still an issue.  

<img width="619" alt="screenshot 2015-10-07 12 26 26" src="https://cloud.githubusercontent.com/assets/630113/10343952/a2fa7802-6cee-11e5-9ed0-e810e496b9c8.png">

**Comment by sometheycallme** [comment]
you have to provide a new registration key / license every time you start?

**Comment by jcwx** [comment]
> If you destroy the container with docker rm or docker rim and then docker build or docker run the new build, attempting to use the same registration key sent to you will NOT work.

> The hash that nessus generates to register the scanner that you intend to use is tied to the installation.

The way I do it, there is no registration after both the Nessus & data containers are created.  I can start & stop the Nessus container as you mentioned, and it's fine, it's when you stop and delete Nessus container, then build a new one where the problem comes into play.  Don't know what factors the install routine uses to create the hash from the reg code.

> you have to provide a new registration key / license every time you start?

Only if the data container is new.

**Comment by sometheycallme** [comment]
There is no data container here.  only the nessusd container and committing the license.key to the image.

>when you stop and delete Nessus container,

yes, and seems to also be if you stop then commit the changes to add license.key to image.

**Comment by jcwx** [comment]
Yesterday, once the Nessus install on IC-IMAP01 was completed, the install totalled 3.5 gig after the plugins were updated.

Also, the license used on that server (the one that started with a 'G' as I recall) was reset yesterday, and won't be available for another reset for 10 days.

**Comment by jcwx** [comment]
Unless we have some way of following up with that Nessus manager/salesdroid you know and getting an unlimited refresh cycle set up.

**Comment by jcwx** [comment]
Hmmnn....I thought I had changed the Dockerfile to install Nessus 6.  

Something is amiss.

**Comment by sometheycallme** [comment]
I'm going to try this again, except this time not use the CLI to register offline.

**Comment by sometheycallme** [comment]
sure enough, when I restart the container after registering via the GUI DRM Wall, still get the same error.

Logs

```cat /opt/nessus/var/nessus/logs/nessusd.messages```

[Wed Oct  7 19:27:18 2015][64.1] received the TERM signal 
[Wed Oct  7 19:40:37 2015][12.1] nessusd 6.4.3 (build M20035) started 
[Wed Oct  7 19:40:37 2015][12.1] Linux overcommit_memory policy is set to: 0 
[Wed Oct  7 19:40:37 2015][12.1] System has 978MB of RAM 
[Wed Oct  7 19:40:37 2015][12.1] Disabled legacy NTP support 
[Wed Oct  7 19:40:40 2015][12.3] Setting the thread pool size to default 
[Wed Oct  7 19:40:40 2015][12.3] Nessus Web Server is running (pid=26) 
[Wed Oct  7 19:42:23 2015][12.51] nessusd-reloader: started
<b>[Wed Oct  7 19:42:25 2015][12.1] Could not validate the license used on this scanner </b>
[Wed Oct  7 19:42:25 2015][12.1] Could not validate plugin feed 
[Wed Oct  7 19:42:25 2015][12.1] nessusd is ready 
[Wed Oct  7 19:42:25 2015][12.1] Redirecting debugging output to /opt/nessus/var/nessus/logs/nessusd.dump 
[root@3e60d8276ad7 /]# cat /opt/nessus/var/nessus/logs/nessusd.dump     
[Wed Oct  7 18:44:56 2015][64.76114] Defragmenting the DB... 
[Wed Oct  7 19:06:12 2015][64.76114] Defragmenting the DB... Done!

**Comment by sometheycallme** [comment]
hmmm, looks like Nessus may track to the mac-address as @jumanjiman and I discussed.

https://discussions.tenable.com/thread/2900

**Comment by jumanjiman** [comment]
then you can `docker run ... --mac-address <spoof>` for repeatability.

you just have to ensure we don't violate the intent of the license (i.e., number of scanners)

**Comment by sometheycallme** [comment]
>you just have to ensure we don't violate the intent of the license (i.e., number of scanners)

intent.  our intent is to get a working scanner inside a single container that we can repeatedly stop, start, and commit changes to.  our intent is to adhere to nessus licensing agreements, of course.

https://docs.docker.com/reference/run/

I'll replace spoofed with a unicast mac address randomly generated. 

```
docker run -d --name nessusd --mac-address <spoofed> -p 8834:8834 sometheycallme:docker-nessus
```

```
[root@localhost docker-splunk]# docker images
REPOSITORY                    TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
<none>                        <none>              3b6a5df2fd89        2 minutes ago       321.4 MB
docker.io/gliderlabs/alpine   latest              3adc3de69ee5        4 months ago        5.238 MB
docker.io/centos              latest              fd44297e2ddb        5 months ago        215.7 MB
[root@localhost docker-splunk]# 
[root@localhost docker-splunk]# docker tag 3b6a5df2fd89 docker:unlicensed
```

**Comment by sometheycallme** [comment]
After running the command to statically set the mac-address, Nessus successfully initializes after committing the changes.


### The procedure updated

1) Pull the container from [hub.docker.com](https://hub.docker.com/r/sometheycallme/docker-nessus/)

```docker pull sometheycallme/docker-nessus```

or git clone the [repo](https://github.com/cleanerbot/docker-nessus)

```git clone git@github.com:cleanerbot/docker-nessus.git```

2) Start the container running with static mac assigned.  I named it ```nessus-unlicensed```

replace <spoofed> with a unique static unicast MAC

```docker run -d --name nessus-unlicensed --mac-address <spoofed> -p 8834:8834 sometheycallme:docker-nessus```

3) Add the license to the running nessus-unlicensed container

You can choose to use the command line (offline registration) or simply provide the unique key in the Web UI after Nessus starts - it will be the one Tenable sends you after you properly register the scanner

4) Stop the container and commit

I name the new container ```nessus:licensed``` and use ```docker images``` command to confirm its creation.  This new container will not be pushed to a public repository.  It will be used in a private repository as our own properly licensed container.

```
docker ps
docker stop <container ID>
docker ps -a
docker commit <container ID> <image-name>
docker images
```

output 
```
[root@localhost docker-nessus]# docker commit 3716bc76dce8 nessus:licensed
d05e0a602768de6b26da76f3ad2dd503e8fd019fa8477d87fefb84be043cf341
[root@localhost docker-nessus]# 
[root@localhost docker-nessus]# docker images
REPOSITORY                    TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
nessus                        licensed            d05e0a602768        7 minutes ago       3.87 GB
```

5) Run the newly created container

Replace <spoofed> with a unique unicast mac-address

```docker run -d --name nessus-licensed --mac-address <spoofed> -p 8834:8834 nessus:licensed```

6) Creating a production container

Once this container is created it would need to be usable internally.  Export the container, import the container, and push to a private docker registry for internal use only.

obviously, name the tarball and ensure quay is setup.

```
docker export <tarball_name>
docker import <tarball_name>
docker push <quay.io>
```

**Comment by jcwx** [comment]
I had suspicions that the mac address on the Nessus container was tied to the hash that was generated with the license key.

**Comment by sometheycallme** [comment]
This issue is resolved.  Procedures added to the repo for those that want to run Nessusd in a container.

Next up - separating the parsing scripts from the data and creating a data container.

**Comment by jcwx** [comment]
Apparently if you're accessing a docker registry server, local or not, you're forced to use TLS.  My local docker registry server takes exception to the change (as it existed before the heavy hand of 'ye shall have no choice' decided for us), therefor I have to either add TLS to the config, or tell the service to run in an insecure mode.  Instructions seem to float about as to how to go about doing that.
